/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as PortfolioSlugEventRouteImport } from './routes/portfolio.$slug.$event'
import { Route as ApiPortfolioAlbumsRouteImport } from './routes/api/portfolio/albums'
import { Route as ApiAdminUploadUrlRouteImport } from './routes/api/admin/upload-url'
import { Route as ApiAdminSaveAlbumRouteImport } from './routes/api/admin/save-album'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminAlbumsRouteImport } from './routes/api/admin/albums'
import { Route as PortfolioSlugEventAlbumRouteImport } from './routes/portfolio.$slug.$event.$album'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugEventRoute = PortfolioSlugEventRouteImport.update({
  id: '/$event',
  path: '/$event',
  getParentRoute: () => PortfolioSlugRoute,
} as any)
const ApiPortfolioAlbumsRoute = ApiPortfolioAlbumsRouteImport.update({
  id: '/api/portfolio/albums',
  path: '/api/portfolio/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadUrlRoute = ApiAdminUploadUrlRouteImport.update({
  id: '/api/admin/upload-url',
  path: '/api/admin/upload-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSaveAlbumRoute = ApiAdminSaveAlbumRouteImport.update({
  id: '/api/admin/save-album',
  path: '/api/admin/save-album',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAlbumsRoute = ApiAdminAlbumsRouteImport.update({
  id: '/api/admin/albums',
  path: '/api/admin/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugEventAlbumRoute = PortfolioSlugEventAlbumRouteImport.update({
  id: '/$album',
  path: '/$album',
  getParentRoute: () => PortfolioSlugEventRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRouteWithChildren
  '/api/admin/albums': typeof ApiAdminAlbumsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/save-album': typeof ApiAdminSaveAlbumRoute
  '/api/admin/upload-url': typeof ApiAdminUploadUrlRoute
  '/api/portfolio/albums': typeof ApiPortfolioAlbumsRoute
  '/portfolio/$slug/$event': typeof PortfolioSlugEventRouteWithChildren
  '/portfolio/$slug/$event/$album': typeof PortfolioSlugEventAlbumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRouteWithChildren
  '/api/admin/albums': typeof ApiAdminAlbumsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/save-album': typeof ApiAdminSaveAlbumRoute
  '/api/admin/upload-url': typeof ApiAdminUploadUrlRoute
  '/api/portfolio/albums': typeof ApiPortfolioAlbumsRoute
  '/portfolio/$slug/$event': typeof PortfolioSlugEventRouteWithChildren
  '/portfolio/$slug/$event/$album': typeof PortfolioSlugEventAlbumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRouteWithChildren
  '/api/admin/albums': typeof ApiAdminAlbumsRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/save-album': typeof ApiAdminSaveAlbumRoute
  '/api/admin/upload-url': typeof ApiAdminUploadUrlRoute
  '/api/portfolio/albums': typeof ApiPortfolioAlbumsRoute
  '/portfolio/$slug/$event': typeof PortfolioSlugEventRouteWithChildren
  '/portfolio/$slug/$event/$album': typeof PortfolioSlugEventAlbumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chi-siamo'
    | '/sitemap.xml'
    | '/categoria/$slug'
    | '/portfolio/$slug'
    | '/api/admin/albums'
    | '/api/admin/login'
    | '/api/admin/save-album'
    | '/api/admin/upload-url'
    | '/api/portfolio/albums'
    | '/portfolio/$slug/$event'
    | '/portfolio/$slug/$event/$album'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chi-siamo'
    | '/sitemap.xml'
    | '/categoria/$slug'
    | '/portfolio/$slug'
    | '/api/admin/albums'
    | '/api/admin/login'
    | '/api/admin/save-album'
    | '/api/admin/upload-url'
    | '/api/portfolio/albums'
    | '/portfolio/$slug/$event'
    | '/portfolio/$slug/$event/$album'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chi-siamo'
    | '/sitemap.xml'
    | '/categoria/$slug'
    | '/portfolio/$slug'
    | '/api/admin/albums'
    | '/api/admin/login'
    | '/api/admin/save-album'
    | '/api/admin/upload-url'
    | '/api/portfolio/albums'
    | '/portfolio/$slug/$event'
    | '/portfolio/$slug/$event/$album'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChiSiamoRoute: typeof ChiSiamoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  PortfolioSlugRoute: typeof PortfolioSlugRouteWithChildren
  ApiAdminAlbumsRoute: typeof ApiAdminAlbumsRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminSaveAlbumRoute: typeof ApiAdminSaveAlbumRoute
  ApiAdminUploadUrlRoute: typeof ApiAdminUploadUrlRoute
  ApiPortfolioAlbumsRoute: typeof ApiPortfolioAlbumsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug/$event': {
      id: '/portfolio/$slug/$event'
      path: '/$event'
      fullPath: '/portfolio/$slug/$event'
      preLoaderRoute: typeof PortfolioSlugEventRouteImport
      parentRoute: typeof PortfolioSlugRoute
    }
    '/api/portfolio/albums': {
      id: '/api/portfolio/albums'
      path: '/api/portfolio/albums'
      fullPath: '/api/portfolio/albums'
      preLoaderRoute: typeof ApiPortfolioAlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload-url': {
      id: '/api/admin/upload-url'
      path: '/api/admin/upload-url'
      fullPath: '/api/admin/upload-url'
      preLoaderRoute: typeof ApiAdminUploadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/save-album': {
      id: '/api/admin/save-album'
      path: '/api/admin/save-album'
      fullPath: '/api/admin/save-album'
      preLoaderRoute: typeof ApiAdminSaveAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/albums': {
      id: '/api/admin/albums'
      path: '/api/admin/albums'
      fullPath: '/api/admin/albums'
      preLoaderRoute: typeof ApiAdminAlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug/$event/$album': {
      id: '/portfolio/$slug/$event/$album'
      path: '/$album'
      fullPath: '/portfolio/$slug/$event/$album'
      preLoaderRoute: typeof PortfolioSlugEventAlbumRouteImport
      parentRoute: typeof PortfolioSlugEventRoute
    }
  }
}

interface PortfolioSlugEventRouteChildren {
  PortfolioSlugEventAlbumRoute: typeof PortfolioSlugEventAlbumRoute
}

const PortfolioSlugEventRouteChildren: PortfolioSlugEventRouteChildren = {
  PortfolioSlugEventAlbumRoute: PortfolioSlugEventAlbumRoute,
}

const PortfolioSlugEventRouteWithChildren =
  PortfolioSlugEventRoute._addFileChildren(PortfolioSlugEventRouteChildren)

interface PortfolioSlugRouteChildren {
  PortfolioSlugEventRoute: typeof PortfolioSlugEventRouteWithChildren
}

const PortfolioSlugRouteChildren: PortfolioSlugRouteChildren = {
  PortfolioSlugEventRoute: PortfolioSlugEventRouteWithChildren,
}

const PortfolioSlugRouteWithChildren = PortfolioSlugRoute._addFileChildren(
  PortfolioSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChiSiamoRoute: ChiSiamoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  PortfolioSlugRoute: PortfolioSlugRouteWithChildren,
  ApiAdminAlbumsRoute: ApiAdminAlbumsRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminSaveAlbumRoute: ApiAdminSaveAlbumRoute,
  ApiAdminUploadUrlRoute: ApiAdminUploadUrlRoute,
  ApiPortfolioAlbumsRoute: ApiPortfolioAlbumsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
